# Generated by Django 4.1.4 on 2022-12-30 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Travel_Agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bus',
            name='agency',
        ),
        migrations.DeleteModel(
            name='Agency',
        ),
        migrations.AlterField(
            model_name='bus',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Travel_Agency.destination'),
        ),
    ]
