# Generated by Django 4.1.4 on 2023-01-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel_Agency', '0002_destination_remove_bus_agency_delete_agency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookbus',
            name='destination',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookbus',
            name='bus',
            field=models.CharField(max_length=100),
        ),
    ]
